version: '3'
services:
  python3:
    # restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'python3_practice'
    working_dir: '/root/opt'
    tty: true
    volumes:
      - ./script:/root/opt
